import Head from 'next/head'
import { Col, Row, Container } from "react-bootstrap";
import styles from "../styles/Home.module.css";
import Background from "../components/Particle/Particle";
import Typewriter from "../components/Typewriter/Typewriter";
import Social from '../components/Socials/Social';



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.homeArea}>
      <div className={styles.homeParticle}>
                    <Background />
                </div>
                <Container>
                    <Row className="justify-content-center">
                        <Col col="12" lg="10">
                            <div className={styles.homeContent}>
                            <h1>Hi, I am <span className={styles.colorTheme}><Typewriter /></span>
                                
                                
                            </h1>
                            <p>I&apos;m a web developer from Scotland. I love to create beautiful, user-friendly, high-converting websites!</p>
                            <Social size="3x" />
                            </div>
                        </Col>
                    </Row>
                </Container>
      </main>

    
    </div>
  )
}
